name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5
      matrix:
        include:
          - python_version: "3.6"
            snakemake_version: "snakemake=4"
          - python_version: "3.10"
            snakemake_version: "snakemake-minimal=5"
          - python_version: "3.10"
            snakemake_version: "snakemake-minimal=6 tabulate=0.8"
          - python_version: "3.11"
            snakemake_version: "snakemake-minimal=7"
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: python
          create-args: >-
            python=${{matrix.python_version}}
            ${{ matrix.snakemake_version }}
          cache-environment: true
          condarc: |
            channels:
              - bioconda
              - conda-forge
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          pip install .
      # - name: Lint with flake8
      #   run: |
      #     conda install flake8
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        shell: bash -el {0}
        run: |
          conda install pytest
          pytest --doctest-modules
